### PR TITLE
Fixup transition model generator for namespaced models

### LINKED ISSUE #460: Generator migration file name inconsistent with class name
# Description

Running the generator for a model under module results in inconsistent filename.

# Reproduction Instruction

`bundle exec rails g statesman:active_record_transition Game::Chess Game::ChessTransition`

# The error

The resulting filename would be `20220324024427_create_chess_transitions.rb`
And the resulting class name would be `class CreateGameChessTransitions < ActiveRecord::Migration[6.1]`

Running this migration results in error:
```
rails aborted!
NameError: uninitialized constant CreateChessTransitions
Did you mean?  CreateGameChessTransitions


Caused by:
NameError: uninitialized constant CreateChessTransitions
Did you mean?  CreateGameChessTransitions
```

# Expected outcome

The generated filename should be consistent with the classname.

`20220324024427_create_game_chess_transitions.rb`

### PR DESCRIPTION
**Pull request by JoeSouthan**
Fixes #460, #546

Namespaced models were not having their transition class generated correctly

Also fixes issue where the model is created after the migration.

Output:

```ruby
# 20250905103710_create_game_chess_transitions.rb
class CreateGameChessTransitions < ActiveRecord::Migration[8.0]
  def change
    create_table :game_chess_transitions do |t|
      t.string :from_state, null: false
      t.string :to_state, null: false
      t.jsonb :metadata, default: {}
      t.integer :sort_key, null: false
      t.integer :game_chess_id, null: false
      t.boolean :most_recent, null: false

      # If you decide not to include an updated timestamp column in your transition
      # table, you'll need to configure the `updated_timestamp_column` setting in your
      # migration class.
      t.timestamps null: false
    end

    # Foreign keys are optional, but highly recommended
    add_foreign_key :game_chess_transitions, :game_chesses

    add_index(:game_chess_transitions,
              %i[game_chess_id sort_key],
              unique: true,
              name: "index_game_chess_transitions_parent_sort")
    add_index(:game_chess_transitions,
              %i[game_chess_id most_recent],
              unique: true,
              where: "most_recent",
              name: "index_game_chess_transitions_parent_most_recent")
  end
end
```

### CODE REVIEW

File: lib/generators/statesman/generator_helpers.rb [hunk 1]
```diff
@@ -10,36 +10,44 @@ def model_file_name
...
+    def association_name
       klass.demodulize.underscore.pluralize
     end
 
+    def table_name
+      klass.underscore.split("/").join("_").tableize
+    end
+
+    def metadata_column_type
+      if ActiveRecord::Base.connection.supports_json?
```
Comment (Tabby) [inline lib/generators/statesman/generator_helpers.rb:34]: Should this not check the connection used by the model rather than `ActiveRecord::Base`, as some models might be using a connection to a different database?

File: lib/generators/statesman/templates/create_migration.rb.erb [hunk 2]
```diff
@@ -1,9 +1,9 @@
-class Create<%= migration_class_name %> < ActiveRecord::Migration<%= "[#{ActiveRecord::Migration.current_version}]" if Statesman::Utils.rails_5_or_higher? %>
+class <%= migration_class_name %> < ActiveRecord::Migration<%= "[#{ActiveRecord::Migration.current_version}]" if Statesman::Utils.rails_5_or_higher? %>
   def change
     create_table :<%= table_name %> do |t|
       t.string :from_state, null: false
       t.string :to_state, null: false
-      t.text :metadata<%= ", default: #{metadata_default_value}" unless mysql? %>
+      t.<%= metadata_column_type %> :metadata<%= ", default: #{metadata_default_value}" unless mysql? %>
```
Comment (Tabby) [inline lib/generators/statesman/templates/create_migration.rb.erb]: nitpick/bikeshed: should we refactor the default value out into a method in `generator_helpers.rb` as well as `metadata_column_type`?

File: lib/generators/statesman/templates/update_migration.rb.erb [hunk 3]
```diff
@@ -1,8 +1,8 @@
-class AddStatesmanTo<%= migration_class_name %> < ActiveRecord::Migration<%= "[#{ActiveRecord::Migration.current_version}]" if Statesman::Utils.rails_5_or_higher? %>
+class <%= migration_class_name %> < ActiveRecord::Migration<%= "[#{ActiveRecord::Migration.current_version}]" if Statesman::Utils.rails_5_or_higher? %>
   def change
     add_column :<%= table_name %>, :from_state, :string, null: false
     add_column :<%= table_name %>, :to_state, :string, null: false
-    add_column :<%= table_name %>, :metadata, :text<%= ", default: #{metadata_default_value}" unless mysql? %>
+    add_column :<%= table_name %>, :metadata, :<%= metadata_column_type %><%= ", default: #{metadata_default_value}" unless mysql? %>
```
Comment (Tabby) [inline lib/generators/statesman/templates/update_migration.rb.erb]: nitpick/bikeshed: should we refactor the default value out into a method in `generator_helpers.rb` as well as `metadata_column_type`?

File: lib/generators/statesman/generator_helpers.rb (hunk 1 above)
Comment (Tabby) [reply lib/generators/statesman/generator_helpers.rb:34]: Actually nah this would be an edge case at best, and a maintenance nightmare if someone were to use different databases with different capabilities for different models so we can probably just say that's unsupported and leave this as-is

**Review by Tabby — APPROVED** [review]
Looks good to me. There's potential for a little more refactoring of the templates, but nothing essential

File: lib/generators/statesman/generator_helpers.rb (hunk 1 above)
Comment (JoeSouthan) [reply lib/generators/statesman/generator_helpers.rb:34]: I think for generators it should be best effort, then it's up to the dev to fixup these details.
